name: Mage run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Test mage:install command without mage
        run: go run main.go mage:install
      - name: Test mage:install command with mage
        run: mage mage:install
      - name: Test mage:install command with mage
        run: mage mage:installversion 1.14.0
