name: Go test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - name: Run with Mage
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: go:test

      - uses: codecov/codecov-action@v3
        with:
          flags: unittests # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)